<?php

/**
 * @file
 * Module file for social_realtime_counter_preprocess_node.
 */

/**
 * Implements hook_preprocess_node().
 */
function social_realtime_counter_preprocess_node(&$variables) {
  $main_urls = $GLOBALS['base_url'];
  $url = $main_urls . '/' . request_path();
  /*check if is view_mode.*/
  if ($variables['view_mode'] == 'full') {
    $node =& $variables['node'];
    /*define sub condition for content type*/
    if ($node->type == 'article' || 'blog') {
      drupal_add_js(array('r_link' => array('urls' => $url)), 'setting');
      drupal_add_js(drupal_get_path('module', 'social_realtime_counter') . '/js/realtime.js');
    }
  }
}
