<?php

/**
* Implements hook_entity_info_alter().
*/
function displayblock_entity_info_alter(&$entity_info) {
    $entity_info['node']['view modes']['block'] = array(
      'label' => t('block'),
      'custom settings' => TRUE,
    );
    $entity_info['node']['view modes']['block_zero'] = array(
      'label' => t('Block Zero'),
      'custom settings' => TRUE,
    );
   $entity_info['node']['view modes']['block_rss'] = array(
    'label' => t('Block RSS'),
    'custom settings' => TRUE,
  );
  $entity_info['node']['view modes']['block_step'] = array(
    'label' => t('Block Step'),
    'custom settings' => TRUE,
  );
   $entity_info['node']['view modes']['block_one'] = array(
    'label' => t('Block One'),
    'custom settings' => TRUE,
  );
  $entity_info['node']['view modes']['block_micro'] = array(
    'label' => t('Block Micro'),
    'custom settings' => TRUE,
  );
  $entity_info['node']['view modes']['block_small'] = array(
    'label' => t('Block Small'),
    'custom settings' => TRUE,
  );
  $entity_info['node']['view modes']['block_sp'] = array(
    'label' => t('Block SP'),
    'custom settings' => TRUE,
  );
  $entity_info['node']['view modes']['block_xp'] = array(
    'label' => t('Block XP'),
    'custom settings' => TRUE,
  );
  $entity_info['node']['view modes']['block_term'] = array(
    'label' => t('Block Term'),
    'custom settings' => TRUE,
  );
}

/**
* Implements hook_preprocess_node().
*/
function displayblock_preprocess_node(&$vars) {
  if($vars['view_mode'] == 'block') {
    $vars['theme_hook_suggestions'][] = 'node__' . $vars['type'] . '__block';
  }
    if($vars['view_mode'] == 'block_zero') {
      $vars['theme_hook_suggestions'][] = 'node__' . $vars['type'] . '__block_zero';}
    
    if($vars['view_mode'] == 'block_rss') {
      $vars['theme_hook_suggestions'][] = 'node__' . $vars['type'] . '__block_rss';
    }

  if($vars['view_mode'] == 'block_step') {
    $vars['theme_hook_suggestions'][] = 'node__' . $vars['type'] . '__block_step';
  }
  if($vars['view_mode'] == 'block_one') {
    $vars['theme_hook_suggestions'][] = 'node__' . $vars['type'] . '__block_one';
  }
  if($vars['view_mode'] == 'block_micro') {
    $vars['theme_hook_suggestions'][] = 'node__' . $vars['type'] . '__block_micro';
  }
  if($vars['view_mode'] == 'block_small') {
    $vars['theme_hook_suggestions'][] = 'node__' . $vars['type'] . '__block_small';
  }
  if($vars['view_mode'] == 'block_sp') {
    $vars['theme_hook_suggestions'][] = 'node__' . $vars['type'] . '__block_sp';
  }
  if($vars['view_mode'] == 'block_xp') {
    $vars['theme_hook_suggestions'][] = 'node__' . $vars['type'] . '__block_xp';
  }
  if($vars['view_mode'] == 'block_term') {
    $vars['theme_hook_suggestions'][] = 'node__' . $vars['type'] . '__block_term';
  }
} 